# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bcbaaa4c645b5ab94642178f57824409a4e1fd675bb6d0cf3bf1267397cbc0b9bf503fa261d7b6bc56c63b60f7bede209d495d0c78f1cf0ccea0de66acf7e33

test:
  secret_key_base: c74bd53ae30dff5c123ec458898c0b1a27ce5cae13b897c2f090fe9fc6d6a09cfc85299d26b24b57ac9f082568759c187b0d00b8a674eda8c7eb016a078ccacc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
